version: "3.4"
services:
  postgres:
    image: postgres:9.6.9
    ports:
      - "5432:5432"
    networks:
      - data_net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  ui:
    build:
      context: ./react
      dockerfile: Dockerfile
      target: dev
    ports:
      - "81:3000"
    networks:
      - data_net
    environment:
      - API_URL=http://localhost:8000 # This is how a browser would call the api
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - ./react:/app
      - /app/node_modules
  api_postgres:
    build:
      context: ./api_postgres
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - data_net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres # The api can address the db by its service name over the docker bridge network
      - DATABASE=postgres
    volumes:
      - ./api_postgres/:/usr/src/app/
  api_sqlserver:
    build:
      context: ./api_sqlserver
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    networks:
      - data_net
    volumes:
      - ./api_sqlserver/:/usr/src/app/
networks:
  data_net:
    external: true
